// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoD8j4e8t1M7RU0ajXjOiVD4NLsY4zX1I',
    appId: '1:793792277549:web:661be7af0b017de5759ca4',
    messagingSenderId: '793792277549',
    projectId: 'petmeofficial-60858',
    authDomain: 'petmeofficial-60858.firebaseapp.com',
    storageBucket: 'petmeofficial-60858.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC_4yrGxhKRnYUWUp2CTLs9pQtdoRZCTA',
    appId: '1:793792277549:android:5035b0346c7b3ef1759ca4',
    messagingSenderId: '793792277549',
    projectId: 'petmeofficial-60858',
    storageBucket: 'petmeofficial-60858.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUVvH0f9QCrlOZmXTYQncAmHqBsofncYA',
    appId: '1:793792277549:ios:5bd459887fbb3754759ca4',
    messagingSenderId: '793792277549',
    projectId: 'petmeofficial-60858',
    storageBucket: 'petmeofficial-60858.appspot.com',
    iosClientId: '793792277549-vp6tforcf7f1qqd599u9a7eshga8e9n2.apps.googleusercontent.com',
    iosBundleId: 'com.FinalYear.petme',
  );
}
